org.gradle.jvmargs=-Xmx2G
org.gradle.workers.max=2
org.gradle.daemon=false
org.gradle.configuration-cache=false

minecraft_version=1.21.1
neo_version=21.1.251
moddev_version=2.0.148

mod_id=rotarycraft
mod_name=RotaryCraft
mod_version=0.1.0
mod_license=MIT
mod_authors=Reika Kalseki (original), Scwunge (1.21.1 port)
group=net.scwunge.rotarycraft
